In [1]:
import numpy as np
from numpy import genfromtxt

### Step1:Gather Data 

In [2]:
data = genfromtxt('Data/bank_note_data.txt',delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

Here is this array is the last column identifies if the note is official(1) or fake (0)

### Step 2: Separate label data and training data 

In [4]:
labels =data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

### Step 3: Split the data for test and train set

In [8]:
X =features
y= labels

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [11]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [12]:
len(X_train)

919

In [13]:
X_test.max()

17.1116

### Step 4: Make a preprocessing step so that neurons can easily identify patterns in the data 

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scaler_object = MinMaxScaler()

Here the fit will only let it know what is min max of data 


* Also we cannot fit X_test cause that causes data leakage will cause un determined behaviour

In [16]:
scaler_object.fit(X_train)

MinMaxScaler()

Now the data has been converted to range from (0 to 1)

In [17]:
scaled_X_train = scaler_object.transform(X_train)

In [18]:
scaled_X_test = scaler_object.transform(X_test)

In [19]:
scaled_X_test.max()

1.02679563427227

### Step5 : Making Model

In [20]:
from keras.models import Sequential
from keras.layers import Dense

In [21]:
model = Sequential()

In [22]:
model.add(Dense(4,input_dim=4,activation='relu')) #input layer
model.add(Dense(8,activation ='relu'))  #hidden layer
model.add(Dense(1,activation='sigmoid'))


C:\Users\vij15\OneDrive\Documents\GitHub\opencvenv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [23]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Step6: Train the Model

In [34]:
model.fit(scaled_X_train,y_train,epochs=100,verbose=2)

Epoch 1/100
29/29 - 0s - 2ms/step - accuracy: 0.9597 - loss: 0.1586
Epoch 2/100
29/29 - 0s - 2ms/step - accuracy: 0.9608 - loss: 0.1540
Epoch 3/100
29/29 - 0s - 2ms/step - accuracy: 0.9608 - loss: 0.1501
Epoch 4/100
29/29 - 0s - 2ms/step - accuracy: 0.9608 - loss: 0.1461
Epoch 5/100
29/29 - 0s - 2ms/step - accuracy: 0.9641 - loss: 0.1424
Epoch 6/100
29/29 - 0s - 2ms/step - accuracy: 0.9641 - loss: 0.1387
Epoch 7/100
29/29 - 0s - 1ms/step - accuracy: 0.9652 - loss: 0.1352
Epoch 8/100
29/29 - 0s - 1ms/step - accuracy: 0.9652 - loss: 0.1323
Epoch 9/100
29/29 - 0s - 1ms/step - accuracy: 0.9663 - loss: 0.1292
Epoch 10/100
29/29 - 0s - 1ms/step - accuracy: 0.9674 - loss: 0.1258
Epoch 11/100
29/29 - 0s - 1ms/step - accuracy: 0.9663 - loss: 0.1231
Epoch 12/100
29/29 - 0s - 1ms/step - accuracy: 0.9684 - loss: 0.1201
Epoch 13/100
29/29 - 0s - 1ms/step - accuracy: 0.9674 - loss: 0.1176
Epoch 14/100
29/29 - 0s - 1ms/step - accuracy: 0.9728 - loss: 0.1153
Epoch 15/100
29/29 - 0s - 1ms/step - accura

### Step7: Now Make Predictions

In [35]:
model.metrics_names

['loss', 'compile_metrics']

In [36]:
from sklearn.metrics import confusion_matrix,classification_report

In [37]:
predictions = (model.predict(scaled_X_test) > 0.5).astype("int32")

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 608us/step


In [38]:
confusion_matrix(y_test,predictions)

array([[254,   3],
       [  2, 194]], dtype=int64)

In [39]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.99      0.99      0.99       257
         1.0       0.98      0.99      0.99       196

    accuracy                           0.99       453
   macro avg       0.99      0.99      0.99       453
weighted avg       0.99      0.99      0.99       453

